SET NAMES utf8mb4;

CREATE TABLE IF NOT EXISTS acc_voucher_rule (
  id BIGINT AUTO_INCREMENT PRIMARY KEY,
  rule_code VARCHAR(50) NOT NULL,
  rule_name VARCHAR(100) NOT NULL,
  business_type VARCHAR(50) NOT NULL,
  business_subtype VARCHAR(50),
  voucher_type INT,
  summary_template VARCHAR(500),
  priority INT DEFAULT 0,
  status INT DEFAULT 1,
  effective_date DATE,
  expiry_date DATE,
  create_time DATETIME,
  update_time DATETIME,
  create_by BIGINT,
  update_by BIGINT,
  deleted INT DEFAULT 0,
  remark VARCHAR(500),
  UNIQUE KEY uk_rule_code (rule_code)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE IF NOT EXISTS acc_voucher_rule_entry (
  id BIGINT AUTO_INCREMENT PRIMARY KEY,
  rule_id BIGINT NOT NULL,
  line_no INT NOT NULL,
  entry_side VARCHAR(10) NOT NULL,
  subject_source VARCHAR(50) NOT NULL,
  subject_code VARCHAR(50),
  subject_formula VARCHAR(500),
  amount_source VARCHAR(50) NOT NULL,
  amount_field VARCHAR(100),
  amount_formula VARCHAR(500),
  amount_fixed DECIMAL(18,2),
  summary_template VARCHAR(500),
  auxiliary_rule VARCHAR(500),
  create_time DATETIME,
  update_time DATETIME,
  create_by BIGINT,
  update_by BIGINT,
  deleted INT DEFAULT 0,
  remark VARCHAR(500),
  KEY idx_rule_id (rule_id)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE IF NOT EXISTS acc_general_ledger (
  id BIGINT AUTO_INCREMENT PRIMARY KEY,
  subject_code VARCHAR(50) NOT NULL,
  subject_name VARCHAR(100),
  period VARCHAR(6) NOT NULL,
  year INT NOT NULL,
  month INT NOT NULL,
  begin_debit DECIMAL(18,2) DEFAULT 0,
  begin_credit DECIMAL(18,2) DEFAULT 0,
  current_debit DECIMAL(18,2) DEFAULT 0,
  current_credit DECIMAL(18,2) DEFAULT 0,
  end_debit DECIMAL(18,2) DEFAULT 0,
  end_credit DECIMAL(18,2) DEFAULT 0,
  create_time DATETIME,
  update_time DATETIME,
  create_by BIGINT,
  update_by BIGINT,
  deleted INT DEFAULT 0,
  remark VARCHAR(500),
  UNIQUE KEY uk_subject_period (subject_code, period)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE IF NOT EXISTS acc_detail_ledger (
  id BIGINT AUTO_INCREMENT PRIMARY KEY,
  subject_code VARCHAR(50) NOT NULL,
  subject_name VARCHAR(100),
  period VARCHAR(6) NOT NULL,
  voucher_id BIGINT,
  voucher_no VARCHAR(50),
  voucher_date VARCHAR(10),
  summary VARCHAR(500),
  debit_amount DECIMAL(18,2) DEFAULT 0,
  credit_amount DECIMAL(18,2) DEFAULT 0,
  direction VARCHAR(4),
  balance DECIMAL(18,2) DEFAULT 0,
  auxiliary_info VARCHAR(500),
  customer_code VARCHAR(50),
  department_code VARCHAR(50),
  project_code VARCHAR(50),
  year INT NOT NULL,
  month INT NOT NULL,
  create_time DATETIME,
  update_time DATETIME,
  create_by BIGINT,
  update_by BIGINT,
  deleted INT DEFAULT 0,
  remark VARCHAR(500),
  KEY idx_subject_period (subject_code, period),
  KEY idx_voucher (voucher_id)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE IF NOT EXISTS acc_period (
  id BIGINT AUTO_INCREMENT PRIMARY KEY,
  period_code VARCHAR(6) NOT NULL,
  period_name VARCHAR(20) NOT NULL,
  year INT NOT NULL,
  month INT NOT NULL,
  start_date DATE NOT NULL,
  end_date DATE NOT NULL,
  status VARCHAR(20) DEFAULT 'OPEN',
  is_current INT DEFAULT 0,
  closing_type VARCHAR(20),
  closing_time DATETIME,
  closing_user_id BIGINT,
  closing_user_name VARCHAR(50),
  create_time DATETIME,
  update_time DATETIME,
  create_by BIGINT,
  update_by BIGINT,
  deleted INT DEFAULT 0,
  remark VARCHAR(500),
  UNIQUE KEY uk_period_code (period_code)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE IF NOT EXISTS acc_carry_forward (
  id BIGINT AUTO_INCREMENT PRIMARY KEY,
  period VARCHAR(6) NOT NULL,
  carry_type VARCHAR(30) NOT NULL,
  source_subject_code VARCHAR(50),
  target_subject_code VARCHAR(50),
  amount DECIMAL(18,2),
  voucher_id BIGINT,
  voucher_no VARCHAR(50),
  status VARCHAR(20) DEFAULT 'PENDING',
  create_time DATETIME,
  update_time DATETIME,
  create_by BIGINT,
  update_by BIGINT,
  deleted INT DEFAULT 0,
  remark VARCHAR(500),
  KEY idx_period (period)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE IF NOT EXISTS acc_financial_report (
  id BIGINT AUTO_INCREMENT PRIMARY KEY,
  report_code VARCHAR(50) NOT NULL,
  report_name VARCHAR(100) NOT NULL,
  report_type VARCHAR(30) NOT NULL,
  period VARCHAR(6) NOT NULL,
  year INT NOT NULL,
  month INT NOT NULL,
  report_data TEXT,
  status VARCHAR(20) DEFAULT 'DRAFT',
  confirm_user_id BIGINT,
  confirm_user_name VARCHAR(50),
  confirm_time DATETIME,
  approve_user_id BIGINT,
  approve_user_name VARCHAR(50),
  approve_time DATETIME,
  create_time DATETIME,
  update_time DATETIME,
  create_by BIGINT,
  update_by BIGINT,
  deleted INT DEFAULT 0,
  remark VARCHAR(500),
  UNIQUE KEY uk_report_code_period (report_code, period)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE IF NOT EXISTS acc_report_template (
  id BIGINT AUTO_INCREMENT PRIMARY KEY,
  template_code VARCHAR(50) NOT NULL,
  template_name VARCHAR(100) NOT NULL,
  report_type VARCHAR(30) NOT NULL,
  template_content TEXT NOT NULL,
  is_default INT DEFAULT 0,
  status INT DEFAULT 1,
  create_time DATETIME,
  update_time DATETIME,
  create_by BIGINT,
  update_by BIGINT,
  deleted INT DEFAULT 0,
  remark VARCHAR(500),
  UNIQUE KEY uk_template_code (template_code)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE IF NOT EXISTS bank_reconciliation_log (
  id BIGINT AUTO_INCREMENT PRIMARY KEY,
  reconciliation_id BIGINT,
  log_type VARCHAR(30),
  bank_transaction_id BIGINT,
  book_bill_id BIGINT,
  book_bill_type VARCHAR(30),
  match_rule VARCHAR(50),
  match_score DECIMAL(5,2),
  operator_id BIGINT,
  operator_name VARCHAR(50),
  description VARCHAR(500),
  create_time DATETIME,
  update_time DATETIME,
  create_by BIGINT,
  update_by BIGINT,
  deleted INT DEFAULT 0,
  remark VARCHAR(500)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE IF NOT EXISTS bank_sync_log (
  id BIGINT AUTO_INCREMENT PRIMARY KEY,
  account_id BIGINT NOT NULL,
  sync_type VARCHAR(30) NOT NULL,
  sync_status VARCHAR(20) NOT NULL,
  request_data TEXT,
  response_data TEXT,
  error_message VARCHAR(500),
  duration_ms BIGINT,
  create_time DATETIME,
  update_time DATETIME,
  create_by BIGINT,
  update_by BIGINT,
  deleted INT DEFAULT 0,
  remark VARCHAR(500)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;
